### PR TITLE
🩹 [AUDIT] Fix blend strategy

### LINKED ISSUE #469: blend strategy: propagate error
In deposit, `update_rate`'s error isn’t propagated (https://github.com/paltalabs/defindex/blob/cde24931a2c2714c74c50200d5d73154ce95b34f/apps/contracts/strategies/blend/src/reserves.rs#L107), so an arithmetic error won’t abort execution - it just won’t update the rate.

### LINKED ISSUE #471: blend strategy: add require auth
harvest emits an event with the caller address (https://github.com/paltalabs/defindex/blob/cde24931a2c2714c74c50200d5d73154ce95b34f/apps/contracts/strategies/blend/src/lib.rs#L209) but doesn’t require auth from him, so anyone can spoof the address(i.e. include a fake caller).

### LINKED ISSUE #472: blend strategy: withdraw should claim and perform reinvest before executing
withdraw should claim emissions and perform_reinvest before executing - similarly to deposit (https://github.com/paltalabs/defindex/blob/cde24931a2c2714c74c50200d5d73154ce95b34f/apps/contracts/strategies/blend/src/lib.rs#L162-L165).  As a rule of thumb, internal accounting must always be up-to-date before changing stake balances(deposit/withdraw).

### LINKED ISSUE #473: blend  stratgegy: review deadline check
Minor issue: The deadline check isn’t enforced properly (https://github.com/paltalabs/defindex/blob/cde24931a2c2714c74c50200d5d73154ce95b34f/apps/contracts/strategies/blend/src/blend_pool.rs#L255) and will always succeed (https://github.com/soroswap/core/blob/fdc28f6b0d422263ba509b2ebbc573ac1b897aec/contracts/router/src/lib.rs#L33-L34), since e.ledger().timestamp() + 600 >=e.ledger().timestamp() will always hold - even without the +600. This is probably not a concern in the perform_reinvest context though.

### PR DESCRIPTION
**Pull request by MattPoblete**
This pull request fix minor issues in the blend strategy contract:
- [x] Propagating update_reserve errors on deposit to resolve #469 
- [x] Add require auth to avoid spoffing on harvest and resolve #471 
- [x] Add claim and perform reinvest to resolve #472 
- [x] Add ensure deadline method to resolve #473

### CODE REVIEW

File: apps/contracts/strategies/blend/src/blend_pool.rs
Comment (esteblock) [inline apps/contracts/strategies/blend/src/blend_pool.rs:1]: we dont need this function

File: apps/contracts/strategies/blend/src/blend_pool.rs [hunk 1]
```diff
@@ -258,6 +272,8 @@ pub fn perform_reinvest(e: &Env, config: &Config) -> Result<bool, StrategyError>
         .checked_add(600)
```
Comment (esteblock) [inline apps/contracts/strategies/blend/src/blend_pool.rs:272]: just remove +600 and let
```
let deadline = e
        .ledger()
        .timestamp();
```

File: apps/contracts/strategies/blend/src/blend_pool.rs [hunk 2]
```diff
@@ -37,6 +37,20 @@ impl RequestType {
...
 
+/// Panics if the specified deadline has passed.
+///
+/// # Arguments
+/// * `e` - The runtime environment.
+/// * `timestamp` - The deadline timestamp to compare against the current ledger timestamp.
+fn ensure_deadline(e: &Env, timestamp: u64) -> Result<(), StrategyError> {
+    let ledger_timestamp = e.ledger().timestamp();
+    if ledger_timestamp >= timestamp {
+        Err(StrategyError::DeadlineExpired)
```
Comment (esteblock) [inline apps/contracts/strategies/blend/src/blend_pool.rs:48]: remove this error
